export interface IStudent {
  /** Some APIs use `studentId`, some use `id` */
  studentId?: number;
  id?: number;
  seqNo?: number;
  bookNo?: string | null;
  groupName?: string | null;
  classSectionId?: number;
  stuId?: string;
  stuName?: string;
  stuPhoto?: string;
  stuThumbPhoto?: string;
  stuDob?: string;
  stuDoa?: string;
  stuGender?: string;
  stuAdmission?: string;
  stuMobile?: string;
  stuEmail?: string;
  height?: string;
  weight?: string;
  bloodGroup?: string;
  caste?: string;
  category?: string;
  religion?: string;
  fatherOccupation?: string;
  fatherQualification?: string;
  motherOccupation?: string;
  motherQualification?: string;
  motherName?: string;
  pincode?: string;
  communicationAddress?: string;
  address?: string;
  city?: string;
  state?: string;
  gaurdianName?: string;
  mobile?: string;
  fatherPhoto?: string;
  motherPhoto?: string;
  parentId?: number;
  rollNumber?: string;
  houseName?: string;
  houseId?: number;
  categoryName?: string;
  categoryId?: number;
  ssmid?: string;
  visonL?: string;
  visionR?: string;
  aadharNo?: string;
  aadhaarNo?: string | null;
  nationality?: string;
  courseName?: string;
  courseId?: number;
  feeSerialNo?: string;
  remark?: string;
  bsano?: string;
  penNo?: string | null;
  apaar?: string | null;
  fatherAadhar?: string | null;
  motherAadhar?: string | null;

  /** Legacy/local fields retained for existing callers. */
  admissionNo?: string;
  studentName?: string; // full name
  firstName?: string;
  lastName?: string;
  className?: string;
  sectionName?: string;
  rollNo?: string | number;
  phone?: string;
  email?: string;
  fatherName?: string;
}
